# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

check.file.structure <- function(filename) {
    .Call('_rgeap_checkFileStructure', PACKAGE = 'rgeap', filename)
}

track.matching.lines <- function(filename, matchLines, prefixOnly = FALSE, lineFeedOnly = TRUE, binOffset = 0L, maxBinRead = -1L) {
    .Call('_rgeap_trackMatchingLines', PACKAGE = 'rgeap', filename, matchLines, prefixOnly, lineFeedOnly, binOffset, maxBinRead)
}

track.matching.string.binpos <- function(filename, candidateStrings, binOffset = 0L, maxBinRead = -1L, lineStartOnly = TRUE) {
    .Call('_rgeap_trackMatchingStringBinPos', PACKAGE = 'rgeap', filename, candidateStrings, binOffset, maxBinRead, lineStartOnly)
}

track.next.line.binpos <- function(filename, binOffset = 0L, skipLines = 0L) {
    .Call('_rgeap_trackNextLineBinPos', PACKAGE = 'rgeap', filename, binOffset, skipLines)
}

read.bin2buffer <- function(filename, skip, binLen, objPtr) {
    .Call('_rgeap_readBin2Mem', PACKAGE = 'rgeap', filename, skip, binLen, objPtr)
}

clean.opened.streams <- function() {
    .Call('_rgeap_cleanOpenedStreams', PACKAGE = 'rgeap')
}

substr.multi <- function(text, starts, sizes) {
    .Call('_rgeap_multiSubstring', PACKAGE = 'rgeap', text, starts, sizes)
}

max.index <- function(vals) {
    .Call('_rgeap_max_index', PACKAGE = 'rgeap', vals)
}

str.size <- function(str) {
    .Call('_rgeap_str_size', PACKAGE = 'rgeap', str)
}

min.index <- function(vals) {
    .Call('_rgeap_min_index', PACKAGE = 'rgeap', vals)
}

internal.ptr <- function(obj) {
    .Call('_rgeap_internalPtr', PACKAGE = 'rgeap', obj)
}

.get.mem.address <- function(obj, outMemInfo = FALSE) {
    .Call('_rgeap_getMemAddress', PACKAGE = 'rgeap', obj, outMemInfo)
}

rawPtr <- function(raw) {
    .Call('_rgeap_rawPtr', PACKAGE = 'rgeap', raw)
}

fixedRawPtr <- function() {
    .Call('_rgeap_fixedRawPtr', PACKAGE = 'rgeap')
}

rawToCharVec <- function(raw, firstOnly = FALSE) {
    .Call('_rgeap_rawToCharVec', PACKAGE = 'rgeap', raw, firstOnly)
}

charVecToRaw <- function(strvec) {
    .Call('_rgeap_charVecToRaw', PACKAGE = 'rgeap', strvec)
}

hasMinByteSize <- function(obj, minSize) {
    .Call('_rgeap_hasMinByteSize', PACKAGE = 'rgeap', obj, minSize)
}

printPtrBytes <- function(ptr, byteCount = 8L) {
    .Call('_rgeap_printPtrBytes', PACKAGE = 'rgeap', ptr, byteCount)
}

multifactor.rebuild.base <- function(indexes, sizes, levels) {
    .Call('_rgeap_multiFactorRebuild', PACKAGE = 'rgeap', indexes, sizes, levels)
}

